version: "3.9"

services:
  # =========================================================================
  # NHÓM 1: CÁC SERVICE CỦA BẠN (CUSTOM IAST)
  # =========================================================================

  frontend:
    image: kienngo22022002/frontend:iast
    pull_policy: never
    container_name: frontend
    restart: always
    # [FIX PORT] Đổi sang 8090 để không đụng Jenkins (8080)
    # Bên trái là cổng Server (8090), Bên phải là cổng Container (8080)
    ports:
      - "8095:8080"
    environment:
      - PORT=8080
      - PRODUCT_CATALOG_SERVICE_ADDR=productcatalogservice:3550
      - CURRENCY_SERVICE_ADDR=currencyservice:7000
      - CART_SERVICE_ADDR=cartservice:7070
      - RECOMMENDATION_SERVICE_ADDR=recommendationservice:8080
      - SHIPPING_SERVICE_ADDR=shippingservice:50051
      - CHECKOUT_SERVICE_ADDR=checkoutservice:5050
      - AD_SERVICE_ADDR=adservice:9555
      - SHOPPING_ASSISTANT_SERVICE_ADDR=shopping-assistant:8080
      # Seeker Config
      - SEEKER_SERVER_URL=http://192.168.12.190:8082
      - SEEKER_PROJECT_KEY=microservices-demo

  paymentservice:
    image: kienngo22022002/paymentservice:iast
    pull_policy: never
    container_name: paymentservice
    restart: always
    ports:
      - "50051:50051"
    environment:
      - PORT=50051
      - SEEKER_SERVER_URL=http://192.168.12.190:8082
      - SEEKER_PROJECT_KEY=microservices-demo
      - DISABLE_PROFILER=1
      - DISABLE_DEBUGGER=1

  adservice:
    image: kienngo22022002/adservice:iast
    pull_policy: never
    container_name: adservice
    restart: always
    ports:
      - "9555:9555"
    environment:
      - PORT=9555
      - SEEKER_SERVER_URL=http://192.168.12.190:8082
      - SEEKER_PROJECT_KEY=microservices-demo
      - JAVA_TOOL_OPTIONS=-javaagent:/app/seeker-agent.jar

  # =========================================================================
  # NHÓM 2: CÁC SERVICE CỦA GOOGLE (STANDARD)
  # =========================================================================

    image: gcr.io/google-samples/microservices-demo/cartservice:v0.10.1
    pull_policy: never
    container_name: cartservice
    pull_policy: never
    restart: always
    ports:
      - "7070:7070"
    environment:
      - REDIS_ADDR=redis-cart:6379

  redis-cart:
    image: redis:alpine
    pull_policy: never
    container_name: redis-cart
    restart: always
    ports:
      - "6379:6379"

  currencyservice:
    image: gcr.io/google-samples/microservices-demo/currencyservice:v0.10.1
    pull_policy: never
    container_name: currencyservice
    restart: always
    ports:
      - "7000:7000"
    environment:
      - PORT=7000

  productcatalogservice:
    image: gcr.io/google-samples/microservices-demo/productcatalogservice:v0.10.1
    pull_policy: never
    container_name: productcatalogservice
    restart: always
    ports:
      - "3550:3550"
    environment:
      - PORT=3550

  recommendationservice:
    image: gcr.io/google-samples/microservices-demo/recommendationservice:v0.10.1
    pull_policy: never
    container_name: recommendationservice
    restart: always
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - PRODUCT_CATALOG_SERVICE_ADDR=productcatalogservice:3550

  shippingservice:
    image: gcr.io/google-samples/microservices-demo/shippingservice:v0.10.1
    pull_policy: never
    container_name: shippingservice
    restart: always
    ports:
      - "50051:50051"
    environment:
      - PORT=50051

  checkoutservice:
    image: gcr.io/google-samples/microservices-demo/checkoutservice:v0.10.1
    pull_policy: never
    container_name: checkoutservice
    restart: always
    ports:
      - "5050:5050"
    environment:
      - PORT=5050
      - PRODUCT_CATALOG_SERVICE_ADDR=productcatalogservice:3550
      - SHIPPING_SERVICE_ADDR=shippingservice:50051
      - PAYMENT_SERVICE_ADDR=paymentservice:50051
      - EMAIL_SERVICE_ADDR=emailservice:8080
      - CURRENCY_SERVICE_ADDR=currencyservice:7000
      - CART_SERVICE_ADDR=cartservice:7070

  emailservice:
    image: gcr.io/google-samples/microservices-demo/emailservice:v0.10.1
    pull_policy: never
    container_name: emailservice
    restart: always
    # Cổng nội bộ container là 8080, nhưng ta không map ra ngoài host nên không sợ đụng Jenkins
    environment:
      - PORT=8080
